"""add workspace_id to sessions and choreography

Revision ID: bfccf0a2169f
Revises: 99cf52a0be50
Create Date: 2026-05-05 08:49:32.989932

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bfccf0a2169f'
down_revision: str | Sequence[str] | None = '99cf52a0be50'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choreography_programs', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_choreography_programs_workspace_id'), 'choreography_programs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'choreography_programs', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.add_column('music_analyses', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_music_analyses_workspace_id'), 'music_analyses', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'music_analyses', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.add_column('sessions', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sessions_workspace_id'), 'sessions', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_workspace_id'), table_name='sessions')
    op.drop_column('sessions', 'workspace_id')
    op.drop_constraint(None, 'music_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_music_analyses_workspace_id'), table_name='music_analyses')
    op.drop_column('music_analyses', 'workspace_id')
    op.drop_constraint(None, 'choreography_programs', type_='foreignkey')
    op.drop_index(op.f('ix_choreography_programs_workspace_id'), table_name='choreography_programs')
    op.drop_column('choreography_programs', 'workspace_id')
    # ### end Alembic commands ###
