"""add process_task_id to sessions

Revision ID: 319070b4dea9
Revises: a5a7881165d4
Create Date: 2026-05-01 15:18:29.767538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "319070b4dea9"
down_revision: str | Sequence[str] | None = "a5a7881165d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("process_task_id", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "process_task_id")
    # ### end Alembic commands ###
