"""add choreography tables

Revision ID: aac592d509a9
Revises: 6b02b4ec0d77
Create Date: 2026-04-12 19:10:06.662164

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aac592d509a9"
down_revision: str | Sequence[str] | None = "6b02b4ec0d77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "music_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("audio_url", sa.String(length=500), nullable=False),
        sa.Column("duration_sec", sa.Float(), nullable=False),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("meter", sa.String(length=10), nullable=True),
        sa.Column("structure", sa.JSON(), nullable=True),
        sa.Column("energy_curve", sa.JSON(), nullable=True),
        sa.Column("downbeats", sa.JSON(), nullable=True),
        sa.Column("peaks", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_music_analyses_user_created", "music_analyses", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_music_analyses_user_id"), "music_analyses", ["user_id"], unique=False)
    op.create_table(
        "choreography_programs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("music_analysis_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("discipline", sa.String(length=30), nullable=False),
        sa.Column("segment", sa.String(length=20), nullable=False),
        sa.Column("season", sa.String(length=10), nullable=False),
        sa.Column("layout", sa.JSON(), nullable=True),
        sa.Column("total_tes", sa.Float(), nullable=True),
        sa.Column("estimated_goe", sa.Float(), nullable=True),
        sa.Column("estimated_pcs", sa.Float(), nullable=True),
        sa.Column("estimated_total", sa.Float(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("validation_errors", sa.JSON(), nullable=True),
        sa.Column("validation_warnings", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["music_analysis_id"], ["music_analyses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_choreo_programs_user_created",
        "choreography_programs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_choreography_programs_user_id"), "choreography_programs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_choreography_programs_user_id"), table_name="choreography_programs")
    op.drop_index("ix_choreo_programs_user_created", table_name="choreography_programs")
    op.drop_table("choreography_programs")
    op.drop_index(op.f("ix_music_analyses_user_id"), table_name="music_analyses")
    op.drop_index("ix_music_analyses_user_created", table_name="music_analyses")
    op.drop_table("music_analyses")
    # ### end Alembic commands ###
