#!/usr/bin/env python3
"""Generate docs/INDEX.md from references.bib + docs/**/*.md frontmatter.

Usage:
    uv run python scripts/generate_index.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

DOCS_ROOT = Path("docs")
BIB_PATH = DOCS_ROOT / "references.bib"
INDEX_PATH = DOCS_ROOT / "INDEX.md"

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def parse_bibtex(path: Path) -> list[dict[str, str]]:
    text = path.read_text(encoding="utf-8")
    entries = []
    # Match @article{citekey, ... }
    for match in re.finditer(r"@\w+\{(\w+),\s*(.*?)\n\}", text, re.DOTALL):
        citekey, body = match.group(1), match.group(2)
        fields: dict[str, str] = {"citekey": citekey}
        for m in re.finditer(r"(\w+)\s*=\s*\{(.*?)\},?\s*$", body, re.MULTILINE):
            key, val = m.group(1).lower(), m.group(2)
            fields[key] = val
        entries.append(fields)
    return entries


def _parse_yaml_block(block: str) -> dict[str, Any]:
    """Parse simple key: value YAML without external deps."""
    result: dict[str, Any] = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        key = key.strip()
        val = val.strip()
        # Remove quotes
        if (val.startswith('"') and val.endswith('"')) or (
            val.startswith("'") and val.endswith("'")
        ):
            val = val[1:-1]
        # List
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1]
            if not inner.strip():
                result[key] = []
            else:
                items = []
                for item in inner.split(","):
                    item = item.strip()
                    if (item.startswith('"') and item.endswith('"')) or (
                        item.startswith("'") and item.endswith("'")
                    ):
                        item = item[1:-1]
                    if item:
                        items.append(item)
                result[key] = items
        else:
            result[key] = val
    return result


def parse_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    return _parse_yaml_block(m.group(1))


def _rel(path: Path) -> str:
    return str(path.relative_to(DOCS_ROOT))


def main() -> int:
    # Parse references
    papers = parse_bibtex(BIB_PATH) if BIB_PATH.exists() else []

    # Collect all markdown files
    md_files: list[Path] = []
    for subdir in ["research", "specs", "plans"]:
        md_files.extend(sorted((DOCS_ROOT / subdir).rglob("*.md")))

    # Parse frontmatter
    files_meta: list[dict[str, Any]] = []
    for path in md_files:
        fm = parse_frontmatter(path)
        if fm:
            files_meta.append(
                {
                    "path": path,
                    "rel": _rel(path),
                    "title": fm.get("title", path.stem),
                    "date": fm.get("date", ""),
                    "citekey": fm.get("citekey", ""),
                    "related": fm.get("related", []),
                    "status": fm.get("status", ""),
                }
            )

    # Build lines
    lines: list[str] = [
        "# Documentation Index",
        "",
        "> Auto-generated by `scripts/generate_index.py`. Do not edit manually.",
        "",
        "## Papers (from references.bib)",
        "",
    ]

    for p in papers:
        title = p.get("title", "Untitled")
        year = p.get("year", "")
        citekey = p["citekey"]
        # Find linked research files
        linked = [f for f in files_meta if f["citekey"] == citekey]
        lines.append(f"### {title}")
        if year:
            lines.append(f"**Year:** {year}  **Citekey:** `{citekey}`")
        else:
            lines.append(f"**Citekey:** `{citekey}`")
        if linked:
            lines.append("")
            lines.append("**Linked notes:**")
            for f in linked:
                lines.append(f"- [{f['title']}]({f['rel']})")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Research Notes")
    lines.append("")

    for f in files_meta:
        status_badge = f" [{f['status']}]" if f["status"] else ""
        lines.append(f"- [{f['title']}]({f['rel']}){status_badge}")
        if f["citekey"]:
            lines.append(f"  - Citekey: `{f['citekey']}`")
        if f["related"]:
            rel_links = ", ".join(f"`{r}`" for r in f["related"])
            lines.append(f"  - Related: {rel_links}")

    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {INDEX_PATH} ({len(papers)} papers, {len(files_meta)} notes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
